### ISSUE TITLE
どんなサービス作る？

### ISSUE THREAD

**Issue by taketakebamboo** [AsoGroup-3/2023Dev3Early#1]

**Comment by tarotarotarot** [comment]
一応今のところは掲示板とチャットアプリくらいかな

**Comment by taketakebamboo** [comment]
作るものの例

１：ソーシャルネットワークサービス - Facebook、Twitter、Instagram、LinkedInなど、ユーザー同士がプロフィールを作成し、メッセージや投稿などを通じてコミュニケーションを取るサービスです。

２：メッセージングアプリ - WhatsApp、LINE、Facebook Messenger、WeChatなど、スマートフォンやコンピューター上でユーザー同士がテキスト、音声、画像、ビデオを使ってコミュニケーションを取るサービスです。

３：ビデオ会議サービス - Zoom、Teams、Google Meetなど、リモートワークやリモート学習などでユーザー同士がビデオ通話やチャットを通じてコミュニケーションを取るサービスです。

４：フォーラムサービス - Reddit、Stack Exchangeなど、複数のユーザーが参加し、テキストや画像などを使ってコミュニケーションを取るサービスです。

５：ブログサービス - WordPress、Bloggerなど、個人が記事を投稿し、読者とコメントなどを通じてコミュニケーションを取るサービスです。

６：ビジネスチャットサービス - Slack、Microsoft Teams、LINE WORKSなど、企業内でのコミュニケーションやプロジェクト管理を目的として、ユーザー同士がチャットやファイル共有などを通じてコミュニケーションを取るサービスです。

６：コミュニティサイト - Meetup、Cookpad、Rettyなど、特定のテーマに関心を持つユーザー同士が集まり、イベントやレシピなどを共有してコミュニケーションを取るサービスです。

７：オンラインマーケットプレイス - eBay、Amazonなど、ユーザー同士が商品の購入や販売を通じてコミュニケーションを取るサービスです。

８：デートアプリ - Tinder、Bumble、Pairsなど、ユーザー同士がマッチングして、メッセージのやりとりやデートを通じてコミュニケーションを取るサービスです。

９：オンライン教育サービス - Udemy、Coursera、edX
他にも掲示板とか当てはまりそうです

**Comment by taketakebamboo** [comment]
チームで話し合った結果掲示板を作成する運びとなりました。
他に作りたいものがある方は意見お願いします！！

**Comment by taketakebamboo** [comment]
一定の確率で書き込みが動物になってしまう掲示板
